### ISSUE TITLE
Links alive

### ISSUE THREAD

**Issue by ghost** [skelton/XD_444#1]
You blocked PMs on dingo. This repo still alive, same with gdrive links via wayback. In case you wanna delete all of it. Delete this issue when you read it anyway, you probably already aware and don't care but I just wanted to bring it out there.
PS: Thanks for your hard work over the years.

**Comment by skelton** [comment]
Yeah. I left the Kernel Code in case IS useful for someone to compile something or make changes. Nobody added a single commit though in 2 years...
